# Generated by Django 4.0.3 on 2022-10-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
